# These are single packages that are known to have a a larger number of dependencies

[apache-airflow-all]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["apache-airflow[all]"]

[dask-complete]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["dask[complete]"]

[modin-dask-ray]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["modin[dask, ray]"]

[great-expectations]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["great-expectations"]

[dagster]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["dagster", "dagster-webserver"]

[celery]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["celery[redis, s3]"]

[ray]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["ray[all]"]

[mlflow]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["mlflow[extras]"]

[pandas-profiling]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["pandas-profiling"]

[spacy]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["spacy"]

[transformers]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["transformers[torch, tf]"]

[bokeh]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["bokeh"]

[prefect]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["prefect"]

[apache-beam]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["apache-beam[gcp, aws, azure]"]

[scikit-learn]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["scikit-learn"]

[nltk]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["nltk[all]"]

[tensorflow]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["tensorflow"]

[kedro]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["kedro"]

[luigi]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["luigi"]

[apscheduler]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["apscheduler"]

[ansible]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["ansible"]

[salt]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["salt"]

[fabric]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["fabric"]

[pyinfra]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["pyinfra"]

[fastapi]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["fastapi"]

[flask]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["flask"]

[pyramid]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["pyramid"]

[pyspark]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["pyspark"]

[databricks-connect]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["databricks-connect"]

[scvi-tools]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["scvi-tools"]

[deepchem]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["deepchem"]

[flair]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["flair"]

[stanza]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["stanza"]

[zipline]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["zipline-reloaded"]

[alphalens]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["alphalens"]

[holoviews]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["holoviews"]

[sktime-all-extras]
python_version = "3.9"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["sktime[all-extras]"]

[sktime-all-extras-pandas-2]
python_version = "3.10"
platform_system = "Linux"
datetime = "2024-10-07T14:00:00"
requirements = ["sktime[all-extras-pandas2]"]

[acryl-datahub-all]
python_version = "3.11"
platform_system = "Linux"
datetime = "2024-10-18T00:00:00"
requirements = ["acryl-datahub[all]"]
